In [2]:
import numpy as np

# Image data types and what they mean

In `skimage`, images are simply `numpy` arrays, which support a variety of data types [1](https://numpy.org/doc/stable/user/basics.types.html), i.e. "dtypes". To avoid distorting image intensity (see Rescaling intensity values), we assume that images use the following ranges:

| Data type   |      Range      |  
|:----------|:-------------|
| uint8 |  0 to 255 | 
| uint16 |    0 to 65535   | 
| uint32 | 0 to 2^32 - 1 | 
| float |  -1 to 1 or 0 to 1 | 
| int8 |    -128 to 127   | 
| int16 | -32768 to 32767 |
| int32 | -2^31 to 2^31 - 1 |

Note that float images should be restricted to the range -1 to 1 even though the data type itself can exceed this range; all integer dtypes, on the other hand, have pixel intensities than can span the entire data type range. With a few exceptions, *64-bit (u)int images are not supported*.

Functions in `skimage` are designed so that they accept any of these dtypes, but, for efficinecy, *may return an image of a different dtype* (see Output types). If you need a particular dtype, `skimage` provides utility functions that convert dtypes and properly rescale image intensities (see Input types). You should **neven use** `astype` on an image, because it violates these assumptions about the dtype range:

In [3]:
from skimage.util import img_as_float
image = np.arange(0, 50, 10, dtype=np.uint8)
print(image.astype(np.float)) # These float values are out of range.

print(img_as_float(image))

[ 0. 10. 20. 30. 40.]
[0.         0.03921569 0.07843137 0.11764706 0.15686275]


## Input types

Although we aim to preserve the data range and type of input images, functions may support only a subset of these data-types. In such a case, the input will be converted to the required type (if possible), and warning message printed to the log o=if a memory copy is needed. Type requirements should be noted in the docstrings. 

The following utility functions in the main package are available to developers and users:

| Function name   |      Description      |  
|:----------|:-------------|
| img_as_float | Convert to 64-bit floating point. | 
| img_as_ubyte |    Convert to 8-bit uint.   | 
| img_as_uint | Convert to 16-bit uint. | 
| img_as_int | Convert to 16-bit int. | 

These functions convert images to the desired dtype and *properly rescale their values*:

In [9]:
from skimage.util import img_as_ubyte
image = np.array([0,0.5,1],dtype=float)
img_as_ubyte(image)

array([  0, 128, 255], dtype=uint8)

Be careful! These conversions can result in a loss of precision, since 8 bits cannot hold the same amount of information as 64 bits:

In [11]:
image = np.array([0,0.5,0.503,1],dtype=float)
img_as_ubyte(image)

array([  0, 128, 128, 255], dtype=uint8)

Additionally, some functions take a `preserve_range` argument where a range conversion is convenient but not necessary. For example, interpolation in `transform.warp` requires an image of typ float, whch should have a range in [0,1]. So, by default, input images will be rescaled to this range. However, in some cases, the image values represent physical measurements, such as temperature or rainfall values, that the user does not want rescaled. With 

## Output types

## Working with OpenCV

It is possible that you may need to use an image ce=reated using `skimge` with **OpenCV** or vice versa. OpenCV image data can be accessed (without copying) in NumPy (and, thus, in scikit-image). OpenCv uses BGR (instead of scikit-image's RGB) for color images, and its dtype is uint8 by default (See Image data types and what they mean), BGR stands for Blue Green Red.

### Converting BGR to RGB or vice versa

The color images in `skimage` and OpenCV have 3 dimensions: width, height and color. RGB and BGR use the same color space, except the order of colors is reversed.

Note that in `scikit-image` we usually refer to `rows` and `columns` instead of width and height (see Coordinate conventions).

The following instruction effectively reverses the order of the colors, leaving the rows and columns uneffected:

In [4]:
# image = image[:,:,::-1]

### Using an image from OpenCV with `skimage`

If `cv_image` is an array of unsigned bytes, `skimage` will understand it by default. If you prefer working with floating point images, `img_as_float()` can be used to convert the image:

In [5]:
# from skimage.util import img_as_float
# image = img_as_float(any_opencv_image)

### Using an image from `skimage` with OpenCV

The reverse can be achieved with `img_as_ubyte()`:

In [7]:
# from skimage.util import img_as_ubyte
# cv_image = img_as_float(any_skimage)

## Image processing pipeline

## Rescaling intensity values

## Note about negative values